Update pytest selenium
testery/example-pytest-selenium pull request #7
Opened 2024-05-24 17:35 UTC by SeanRayR

![image](https://github.com/testery/example-pytest-selenium/assets/47629325/ff68eef1-4594-4034-b049-d537a47ff54f)

2024-05-24 19:28 UTC, HeffZilla approved these changes

2024-05-24 20:08 UTC, wgunn-testery requested changes

2024-05-24 20:08 UTC, wgunn-quality commented on README.md
> +```pip install webdriver-manager```
I don't think we need to list these out separately since they are/should be defined in the requirements file.

2024-05-24 20:08 UTC, wgunn-quality commented on README.md
> +2) Set Python as the interpreter in your IDE
I think this title should be "2) Set up virtual environment"
At least based on the link underneath.

2024-05-24 20:08 UTC, wgunn-testery commented on test/conftest.py
I think webdriver_manager is old style. We can simply do this:
```python
import pytest
from selenium import webdriver


@pytest.fixture
def chrome_browser():
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")  # Run Chrome in headless mode
    service = webdriver.ChromeService()
    driver = webdriver.Chrome(options=options, service=service)
    yield driver
    driver.quit()
    ```

2024-05-27 14:30 UTC, SeanRayR commented on README.md
> +```pip install webdriver-manager```
updated

2024-05-27 14:30 UTC, SeanRayR commented on README.md
> +2) Set Python as the interpreter in your IDE
updated

2024-05-27 14:50 UTC, SeanRayR commented on test/conftest.py
also update this

2024-05-28 16:41 UTC, wgunn-testery approved these changes

2024-05-28 17:53 UTC, merged